-- Paste into the SQL editor after schema.sql. Loads the 47 prefectures and the current sample Friends.

insert into prefectures (id,slug,name_en,name_ja,region,description,specialties,seasonal_foods) values
(1,'hokkaido','Hokkaido','北海道','Hokkaido','Japan''s northern larder: cold seas, wide dairy country and potatoes grown in volcanic soil.',array['Kelp','Sea urchin','Crab','Salmon','Dairy','Potatoes']::text[],array['Asparagus','Sea urchin','Salmon','Hairy crab']::text[]),
(2,'aomori','Aomori','青森県','Tohoku','Apple country at the top of Honshu, with garlic farms inland and tuna landed at Ōma.',array['Apples','Garlic','Tuna','Scallops','Chinese yam']::text[],array['Scallops','Garlic','Apples','Ōma tuna']::text[]),
(3,'iwate','Iwate','岩手県','Tohoku','A long rias coastline for oysters and wakame, and a mountain interior known for soba and beef.',array['Wakame seaweed','Oysters','Buckwheat noodles','Maezawa beef','Cold noodles']::text[],array['Wakame seaweed','Sea urchin','Matsutake mushrooms','Oysters']::text[]),
(4,'miyagi','Miyagi','宮城県','Tohoku','Sendai''s grilled beef tongue and zunda mochi, with oyster rafts across Matsushima Bay.',array['Beef tongue','Oysters','Sweet edamame paste','Bamboo-leaf fish cake','Rice']::text[],array['Bamboo shoots','Sea pineapple','Salmon and roe rice','Oysters']::text[]),
(5,'akita','Akita','秋田県','Tohoku','Snow-country rice and sake, smoked pickles, and hotpots of hand-shaped rice.',array['Smoked pickled radish','Grilled rice sticks','Rice','Sake','Fish sauce','Inaniwa udon']::text[],array['Wild vegetables','Water shield','Grilled rice sticks','Sandfish']::text[]),
(6,'yamagata','Yamagata','山形県','Tohoku','Cherries and pears in the valleys, soba in the mountains and riverside imoni stews each autumn.',array['Cherries','Pears','Buckwheat noodles','Taro stew','Dadacha edamame','Rice']::text[],array['Wild vegetables','Cherries','Taro stew','La France pears']::text[]),
(7,'fukushima','Fukushima','福島県','Tohoku','Peach orchards, sake breweries in Aizu and a deep ramen culture in Kitakata.',array['Peaches','Sake','Kitakata ramen','Dried scallop soup','Rice']::text[],array['Bamboo shoots','Peaches','Persimmons','Sake']::text[]),
(8,'ibaraki','Ibaraki','茨城県','Kanto','Farm belt east of Tokyo: natto from Mito, melons, chestnuts and anglerfish hotpot.',array['Fermented soybeans','Melons','Chestnuts','Anglerfish','Lotus root']::text[],array['Melons','Watermelon','Chestnuts','Anglerfish']::text[]),
(9,'tochigi','Tochigi','栃木県','Kanto','Strawberries, yuba from Nikko and the gyoza shops of Utsunomiya.',array['Strawberries','Tofu skin','Gyoza dumplings','Dried gourd strips','Dairy']::text[],array['Strawberries','Dried gourd strips','Buckwheat noodles','Strawberries']::text[]),
(10,'gunma','Gunma','群馬県','Kanto','Konnyaku and wide flat noodles from mountain towns, cabbage from cool plateaus.',array['Konjac','Wide flat noodles','Cabbage','Shimonita leeks','Grilled buns']::text[],array['Wild vegetables','Cabbage','Konjac','Shimonita leeks']::text[]),
(11,'saitama','Saitama','埼玉県','Kanto','Sayama tea, Kawagoe sweet potatoes and soy sauce brewed along the old rivers.',array['Sayama tea','Sweet potatoes','Soy sauce','Taro','Udon noodles']::text[],array['Sayama tea','Edamame','Sweet potatoes','Taro']::text[]),
(12,'chiba','Chiba','千葉県','Kanto','Peanuts, the soy sauce towns of Noda and Chōshi, and a long fishing coast.',array['Peanuts','Soy sauce','Sardines','Loquats','Minced fish tartare']::text[],array['Loquats','Sardines','Peanuts','Nori seaweed']::text[]),
(13,'tokyo','Tokyo','東京都','Kanto','Edomae sushi, market culture and the densest concentration of small restaurants anywhere.',array['Edo-style sushi','Buckwheat noodles','Soy-simmered preserves','Savory griddle batter','Japanese mustard spinach']::text[],array['Early-season bonito','Eel','Buckwheat noodles','Japanese mustard spinach']::text[]),
(14,'kanagawa','Kanagawa','神奈川県','Kanto','Kamaboko from Odawara, whitebait off Shōnan and tangerines on the Miura peninsula.',array['Fish cake','Whitebait','Satsuma mandarin','Miura radish','Tuna']::text[],array['Whitebait','Watermelon','Satsuma mandarin','Miura radish']::text[]),
(15,'niigata','Niigata','新潟県','Chubu','Rice and sake country: Koshihikari paddies fed by snowmelt and clean, dry sake.',array['Rice','Sake','Seaweed buckwheat noodles','Bamboo-leaf rice dumplings','Snow-aged vegetables']::text[],array['Bamboo-leaf rice dumplings','Edamame','New rice','Snow-aged carrots']::text[]),
(16,'toyama','Toyama','富山県','Chubu','Deep Toyama Bay brings firefly squid in spring and yellowtail in winter.',array['Firefly squid','White shrimp','Yellowtail','Trout sushi','Kelp']::text[],array['Firefly squid','White shrimp','Red snow crab','Yellowtail']::text[]),
(17,'ishikawa','Ishikawa','石川県','Chubu','Kanazawa''s refined cooking, ishiru fish sauce from Noto and snow crab in winter.',array['Snow crab','Noto fish sauce','Duck stew','Kaga vegetables','Sake']::text[],array['Firefly squid','Rock oysters','Kaga vegetables','Snow crab']::text[]),
(18,'fukui','Fukui','福井県','Chubu','Echizen crab, heshiko mackerel aged in rice bran, and the old mackerel road to Kyoto.',array['Echizen crab','Rice-bran cured mackerel','Buckwheat noodles with grated radish','Japanese plums','Rice']::text[],array['Japanese plums','Rock oysters','Buckwheat noodles with grated radish','Echizen crab']::text[]),
(19,'yamanashi','Yamanashi','山梨県','Chubu','Grapes, peaches and Japan''s oldest wine country, in basins below Mount Fuji.',array['Grapes','Peaches','Wine','Pumpkin noodle stew','Shingen rice cakes']::text[],array['Cherries','Peaches','Grapes','Pumpkin noodle stew']::text[]),
(20,'nagano','Nagano','長野県','Chubu','High valleys and cold winters: orchards, soba fields and the miso that carries the region''s old name, Shinshu.',array['Grapes','Apples','Peaches','Buckwheat noodles','Miso','Wine']::text[],array['Wild vegetables','Peaches','Grapes','Nozawa greens pickles']::text[]),
(21,'gifu','Gifu','岐阜県','Chubu','River sweetfish, Hida beef and hoba miso grilled on a magnolia leaf.',array['Sweetfish','Hida beef','Magnolia-leaf miso','Chestnuts','Persimmons']::text[],array['Wild vegetables','Sweetfish','Chestnuts','Magnolia-leaf miso']::text[]),
(22,'shizuoka','Shizuoka','静岡県','Chubu','Japan''s largest tea region, with wasabi grown in mountain streams and bonito landed at Yaizu.',array['Tea','Wasabi','Bonito flakes','Sakura shrimp','Satsuma mandarin']::text[],array['First-flush green tea','Melons','Sakura shrimp','Satsuma mandarin']::text[]),
(23,'aichi','Aichi','愛知県','Chubu','Dark miso made from soybeans alone, and a Nagoya food culture built around it.',array['Hatchō miso','Tamari soy sauce','Flat noodles','Nagoya cochin','Miso pork cutlet']::text[],array['Cabbage','Eel','Figs','Miso-simmered noodles']::text[]),
(24,'mie','Mie','三重県','Kansai','Ise lobster, Matsusaka beef and the pearl-farming bays of Shima.',array['Ise lobster','Matsusaka beef','Oysters','Ise tea','Green laver']::text[],array['Green laver','Abalone','Ise lobster','Oysters']::text[]),
(25,'shiga','Shiga','滋賀県','Kansai','Around Lake Biwa: funazushi, one of Japan''s oldest fermented foods, and Ōmi beef.',array['Fermented crucian carp','Ōmi beef','Rice','Sake','Lake fish']::text[],array['Lake Biwa gudgeon','Sweetfish','New rice','Fermented crucian carp']::text[]),
(26,'kyoto','Kyoto','京都府','Kansai','Temple cooking, tofu and yuba, heirloom Kyoto vegetables, and tea from Uji.',array['Matcha','Tofu','Tofu skin','Kyoto vegetables','Sesame','Pickles']::text[],array['Bamboo shoots','Pike conger','Matsutake mushrooms','Shōgoin turnip']::text[]),
(27,'osaka','Osaka','大阪府','Kansai','The nation''s kitchen: dashi-forward cooking, kombu merchants and street food.',array['Kelp','Octopus balls','Savory pancakes','Fried skewers','Water eggplant']::text[],array['Chrysanthemum greens','Water eggplant','Chestnuts','Pufferfish sashimi']::text[]),
(28,'hyogo','Hyogo','兵庫県','Kansai','Kobe beef, the sake breweries of Nada, and sea bream from the Inland Sea.',array['Kobe beef','Sake','Sea bream','Black soybeans','Nori seaweed']::text[],array['Sand lance','Octopus','Black soybeans','Oysters']::text[]),
(29,'nara','Nara','奈良県','Kansai','Said to be where Japanese sake brewing began; persimmon-leaf sushi and hand-pulled somen.',array['Persimmon-leaf sushi','Thin wheat noodles','Persimmons','Nara pickles','Yamato tea']::text[],array['Yamato tea','Thin wheat noodles','Persimmons','Nara pickles']::text[]),
(30,'wakayama','Wakayama','和歌山県','Kansai','Mandarin groves, ume orchards at Minabe and the soy sauce town of Yuasa.',array['Japanese plums','Satsuma mandarin','Soy sauce','Kinzanji miso','Tuna']::text[],array['Plum blossom','Green plums','Satsuma mandarin','Tuna']::text[]),
(31,'tottori','Tottori','鳥取県','Chugoku','Dunes and a snow-crab coast, with Nijisseiki pears in late summer.',array['Snow crab','Pears','Pickled shallots','Tofu fish cake','Beef']::text[],array['Pickled shallots','Rock oysters','Pears','Snow crab']::text[]),
(32,'shimane','Shimane','島根県','Chugoku','Izumo soba, clams from Lake Shinji and old soy sauce and sake breweries along the coast.',array['Buckwheat noodles','Freshwater clams','Soy sauce','Sake','Blackthroat seaperch']::text[],array['Wakame seaweed','Freshwater clams','New-harvest buckwheat noodles','Blackthroat seaperch']::text[]),
(33,'okayama','Okayama','岡山県','Chugoku','The fruit kingdom: white peaches, muscat grapes and a mild, sunny climate.',array['Peaches','Grapes','Marinated sardinella','Millet dumplings','Oysters']::text[],array['Spanish mackerel','White peaches','Muscat grapes','Oysters']::text[]),
(34,'hiroshima','Hiroshima','広島県','Chugoku','Oysters from the Inland Sea, island lemons, and soft-water sake at Saijō.',array['Oysters','Lemons','Sake','Savory pancakes','Conger eel']::text[],array['Conger eel','Lemons','Matsutake mushrooms','Oysters']::text[]),
(35,'yamaguchi','Yamaguchi','山口県','Chugoku','Fugu at Shimonoseki, sea urchin from the Sea of Japan and sweet regional soy sauce.',array['Pufferfish','Sea urchin','Tile-grilled tea noodles','Soy sauce','Fish cake']::text[],array['Sea urchin','Squid','Satsuma mandarin','Pufferfish']::text[]),
(36,'tokushima','Tokushima','徳島県','Shikoku','Sudachi citrus, wasanbon sugar and wakame from the Naruto straits.',array['Sudachi lime','Fine-grain sugar','Wakame seaweed','Lotus root','Awa chicken']::text[],array['Wakame seaweed','Sudachi lime','Sweet potatoes','Lotus root']::text[]),
(37,'kagawa','Kagawa','香川県','Shikoku','Udon country, with olive groves and island soy sauce breweries on Shōdoshima.',array['Udon noodles','Olives','Soy sauce','Dried sardines','Roast chicken leg']::text[],array['Spanish mackerel','Dried sardines','Olives','Udon noodles']::text[]),
(38,'ehime','Ehime','愛媛県','Shikoku','Citrus of every kind on terraced hills, and sea bream rice from the Uwa Sea.',array['Satsuma mandarin','Mandarin orange','Sea bream rice','Fried fish cake','Iyo orange']::text[],array['Iyo orange','Sea bream','Satsuma mandarin','Mandarin orange']::text[]),
(39,'kochi','Kochi','高知県','Shikoku','Bonito seared over straw, yuzu villages in the mountains and ginger by the ton.',array['Seared bonito','Yuzu','Ginger','Salt','Eggplant']::text[],array['Bonito','Eggplant','Yuzu','Pomelo']::text[]),
(40,'fukuoka','Fukuoka','福岡県','Kyushu','Hakata ramen, spicy mentaiko, and gyokuro from the tea hills of Yame.',array['Spicy cod roe','Ramen','Yame tea','Chicken hot pot','Strawberries']::text[],array['Yame tea','Figs','Persimmons','Strawberries']::text[]),
(41,'saga','Saga','佐賀県','Kyushu','Ariake Sea nori, the porcelain towns of Arita and Imari, and Ureshino tea.',array['Nori seaweed','Ureshino tea','Saga beef','Squid','Ceramics']::text[],array['Ureshino tea','Squid','Satsuma mandarin','Nori seaweed']::text[]),
(42,'nagasaki','Nagasaki','長崎県','Kyushu','Centuries of trade in the food: castella, champon and karasumi mullet roe.',array['Castella sponge cake','Seafood noodle soup','Dried mullet roe','Thin wheat noodles','Loquats']::text[],array['Loquats','Squid','Dried mullet roe','Castella sponge cake']::text[]),
(43,'kumamoto','Kumamoto','熊本県','Kyushu','Spring water from Aso, lotus root stuffed with mustard miso, and tomatoes and watermelons.',array['Mustard lotus root','Tomatoes','Watermelon','Sumo citrus']::text[],array['Tomatoes','Watermelon','Chestnuts','Sumo citrus']::text[]),
(44,'oita','Oita','大分県','Kyushu','Log-grown dried shiitake, kabosu citrus and cooking with hot-spring steam.',array['Shiitake','Kabosu lime','Seki mackerel','Chicken tempura','Dumpling soup']::text[],array['Shiitake','Kabosu lime','Seki mackerel','Pufferfish']::text[]),
(45,'miyazaki','Miyazaki','宮崎県','Kyushu','Mangoes, chicken nanban and hyuganatsu citrus in warm southern light.',array['Mango','Fried chicken with tartar sauce','Hyuga summer orange','Free-range chicken','Shochu']::text[],array['Hyuga summer orange','Mango','Chestnuts','Kumquats']::text[]),
(46,'kagoshima','Kagoshima','鹿児島県','Kyushu','Sweet-potato shōchū, Kurobuta pork and katsuobushi from Makurazaki.',array['Shochu','Black Berkshire pork','Bonito flakes','Sweet potatoes','Chiran tea']::text[],array['Chiran tea','Bonito','Sweet potatoes','Sakurajima radish']::text[]),
(47,'okinawa','Okinawa','沖縄県','Okinawa','Subtropical islands: bitter melon, awamori, brown sugar and sea salt.',array['Bitter melon','Okinawan rice spirit','Black sugar','Salt','Mozuku seaweed','Okinawan lime']::text[],array['Mozuku seaweed','Bitter melon','Okinawan lime','Black sugar']::text[])
on conflict (id) do nothing;

-- Snapshot of the original sheet. source='manual' rows are edited in Supabase / via /admin.
insert into friends (slug,no,name_en,name_ja,maker,prefecture,city,latitude,longitude,category,since,makes,specialties,ingredients,methods,tags,description,story,relationship_to_cabi,website,instagram,published) values
('yamada-seiyu',1,'Yamada Seiyu',null,'Kōichi Yamada','kyoto','Kyoto',35.008,135.772,'Producer',null,'Seasonings',array[]::text[],array[]::text[],array[]::text[],array['Seasonings']::text[],null,'',null,null,'@henko_yamada',true),
('morita-shoyu',2,'Morita Shoyu',null,'Ikufumi Morita','shimane','Shimane',35.506,133.014,'Producer',null,'Seasonings',array[]::text[],array[]::text[],array[]::text[],array['Seasonings']::text[],null,'',null,null,null,true),
('akita-konno-shoten',3,'Akita Konno Shoten','秋田今野商店',null,'akita','Akita',39.672,140.148,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('yamada-egg-farm',4,'Yamada Egg Farm','京都大原山田農園',null,'kyoto','Kyoto',35.02,135.76,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('ishikuro-tane-koji',5,'Ishikuro Tane Koji','石黒種麹店',null,'toyama','Toyama',36.748,137.162,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('ine-to-agave',6,'Ine to Agave',null,'Shuhei Okazumi','akita','Akita',39.684,140.136,'Producer',null,'Drinks',array[]::text[],array[]::text[],array[]::text[],array['Drinks']::text[],null,'',null,null,null,true),
('yamamo-brewery',7,'Yamamo Brewery',null,null,'akita','Akita',39.732,140.088,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'yamamo1867.com',null,true),
('isegura',8,'Isegura',null,'Shikii','mie','Mie',34.79,136.45,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('fukudome-farm',9,'Fukudome Farm','ふくどめ小牧場',null,'kagoshima','Kagoshima',31.536,130.584,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('yamaroku',10,'Yamaroku',null,null,'kagawa','Kagawa',34.364,134.016,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('kamikouchi-miso',11,'Kamikouchi Miso',null,'Soichi Akanahe','nagano','Nagano',36.59,138.24,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('kokonoe-saika',12,'Kokonoe Saika',null,'Saika','wakayama','Wakayama',34.218,135.182,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('happy-nuts-day',13,'Happy Nuts Day',null,null,'chiba','Chiba',35.646,140.084,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('bounotsu-no-shio',14,'Bounotsu No Shio',null,null,'kagoshima','Kagoshima',31.512,130.608,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'kurashi-to-oshare.jp/food/171793',null,true),
('kanosuke-distillery',15,'Kanosuke Distillery',null,null,'kagoshima','Kagoshima',31.56,130.56,'Producer',null,'Drinks',array[]::text[],array[]::text[],array[]::text[],array['Drinks']::text[],null,'',null,null,null,true),
('horon',16,'Horon',null,'Rei','tokyo','Tokyo',35.738,139.642,'Producer',null,'Drinks',array[]::text[],array[]::text[],array[]::text[],array['Drinks']::text[],null,'',null,null,null,true),
('friend-17',17,'総本家 喜多品老舗',null,null,'shiga','Shiga',34.964,135.906,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,'@kitashina_funazushi',true),
('from-farm',18,'From Farm',null,'Koji Ootani','wakayama','Wakayama',34.242,135.158,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'from-farm.com',null,true),
('koji-zaemon',19,'Koji Zaemon','麹坐右衛門',null,'aichi','Aichi',35.24,136.85,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'kojiyasanzaemon.store',null,true),
('ethical-spirits',20,'Ethical Spirits',null,'Ayumu Yamaguchi','tokyo','Tokyo',35.666,139.714,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('nitto-jozo',21,'Nitto Jozo','日東醸造',null,'aichi','Aichi',35.204,136.886,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'nitto-j.com',null,true),
('nozawa-onsen-distillery',22,'Nozawa Onsen Distillery',null,null,'nagano','Nagano',36.59,138.24,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('friend-23',23,'ユートピアアグリカルチャー',null,'Naganuma','hokkaido','Hokkaido',43.048,141.362,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'www.utopiaagriculture.com/journal/210218',null,true),
('friend-24',24,'加藤農園',null,null,'tokyo','Tokyo',35.726,139.654,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'kato-farm.com',null,true),
('tea-room',25,'Tea Room',null,null,'shizuoka','Shizuoka',34.932,138.428,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('friend-26',26,'こうじ製造所 中村屋老舗',null,null,'shizuoka','Shizuoka',34.98,138.38,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,null,null,true),
('friend-27',27,'飯尾醸造',null,null,'kyoto','Kyoto',35.068,135.712,'Producer',null,null,array[]::text[],array[]::text[],array[]::text[],array[]::text[],null,'',null,'iio-jozo.co.jp',null,true)
on conflict (slug) do nothing;

-- Photos bundled with the site (served from /assets). New photos go to the `friends` storage bucket instead.
insert into friend_images (friend_id, path, caption, position)
select f.id, v.path, v.caption, v.position from (values
('akita-konno-shoten','assets/friends/akita-konno-shoten/1.jpg','Akita Konno Shoten — 1',0),
('akita-konno-shoten','assets/friends/akita-konno-shoten/2.jpg','Akita Konno Shoten — 2',1),
('akita-konno-shoten','assets/friends/akita-konno-shoten/3.jpg','Akita Konno Shoten — 3',2),
('akita-konno-shoten','assets/friends/akita-konno-shoten/4.jpg','Akita Konno Shoten — 4',3),
('akita-konno-shoten','assets/friends/akita-konno-shoten/5.jpg','Akita Konno Shoten — 5',4),
('akita-konno-shoten','assets/friends/akita-konno-shoten/6.jpg','Akita Konno Shoten — 6',5),
('akita-konno-shoten','assets/friends/akita-konno-shoten/7.jpg','Akita Konno Shoten — 7',6),
('akita-konno-shoten','assets/friends/akita-konno-shoten/8.jpg','Akita Konno Shoten — 8',7),
('akita-konno-shoten','assets/friends/akita-konno-shoten/9.jpg','Akita Konno Shoten — 9',8),
('akita-konno-shoten','assets/friends/akita-konno-shoten/10.jpg','Akita Konno Shoten — 10',9),
('akita-konno-shoten','assets/friends/akita-konno-shoten/11.jpg','Akita Konno Shoten — 11',10),
('akita-konno-shoten','assets/friends/akita-konno-shoten/12.jpg','Akita Konno Shoten — 12',11),
('akita-konno-shoten','assets/friends/akita-konno-shoten/13.jpg','Akita Konno Shoten — 13',12),
('akita-konno-shoten','assets/friends/akita-konno-shoten/14.jpg','Akita Konno Shoten — 14',13),
('akita-konno-shoten','assets/friends/akita-konno-shoten/15.jpg','Akita Konno Shoten — 15',14),
('akita-konno-shoten','assets/friends/akita-konno-shoten/16.jpg','Akita Konno Shoten — 16',15),
('ishikuro-tane-koji','assets/friends/ishikuro-tane-koji/1.jpg','Ishikuro Tane Koji — 1',0),
('ishikuro-tane-koji','assets/friends/ishikuro-tane-koji/2.jpg','Ishikuro Tane Koji — 2',1),
('ishikuro-tane-koji','assets/friends/ishikuro-tane-koji/3.jpg','Ishikuro Tane Koji — 3',2),
('ishikuro-tane-koji','assets/friends/ishikuro-tane-koji/4.jpg','Ishikuro Tane Koji — 4',3),
('ishikuro-tane-koji','assets/friends/ishikuro-tane-koji/5.jpg','Ishikuro Tane Koji — 5',4),
('ine-to-agave','assets/friends/ine-to-agave/1.jpg','Ine to Agave — 1',0),
('ine-to-agave','assets/friends/ine-to-agave/2.jpg','Ine to Agave — 2',1),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/1.jpg','Bounotsu No Shio — 1',0),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/2.jpg','Bounotsu No Shio — 2',1),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/3.jpg','Bounotsu No Shio — 3',2),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/4.jpg','Bounotsu No Shio — 4',3),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/5.jpg','Bounotsu No Shio — 5',4),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/6.jpg','Bounotsu No Shio — 6',5),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/7.jpg','Bounotsu No Shio — 7',6),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/8.jpg','Bounotsu No Shio — 8',7),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/9.jpg','Bounotsu No Shio — 9',8),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/10.jpg','Bounotsu No Shio — 10',9),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/11.jpg','Bounotsu No Shio — 11',10),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/12.jpg','Bounotsu No Shio — 12',11),
('bounotsu-no-shio','assets/friends/bounotsu-no-shio/13.jpg','Bounotsu No Shio — 13',12),
('tea-room','assets/friends/tea-room/1.jpg','Tea Room — 1',0)
) as v(slug, path, caption, position) join friends f on f.slug = v.slug
on conflict (path) do nothing;
